DROP TABLE IF EXISTS `Cidade`;

CREATE TABLE `Cidade` (
  `idCidade` INT AUTO_INCREMENT PRIMARY KEY,
  `nome` VARCHAR(255) NOT NULL,
  `codigoIbge` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;