DROP TABLE IF EXISTS `Bairro`;

CREATE TABLE `Bairro` (
  `idBairro` INT AUTO_INCREMENT PRIMARY KEY,
  `nome` VARCHAR(255) NOT NULL,
  `codigoIbge` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;